# Copyright STARKIT Soccer team of MIPT. Adapted from class_Motion.py.
# Generated by tools/import_motion.py; hardware output is cooperative yield.
# Source SHA256: 166636b23e242952d2d79179b6c13aa26bf3c98f6074f15c87dbd6e725d19b42
import math
import time
from dataclasses import dataclass

uprint = print

@dataclass
class Servo:
    Id: int = 0
    Sio: int = 0
    Data: int = 0

class GaitAlgorithms:

    def computeAlphaForWalk(self, hands_on=True):
        angles = []
        anglesR = []
        anglesL = []
        anglesR = self.solve_leg('right', self.xtr, self.ytr, self.ztr, self.xr, self.yr, self.zr, self.wr, self.SIZES, self.LIMALPHA)
        anglesL = self.solve_leg('left', self.xtl, -self.ytl, self.ztl, self.xl, -self.yl, self.zl, self.wl, self.SIZES, self.LIMALPHA)
        if len(anglesR) > 1:
            for i in range(len(anglesR)):
                if len(anglesR) == 1:
                    break
                if anglesR[0][2] < anglesR[1][2]:
                    anglesR.pop(1)
                else:
                    anglesR.pop(0)
        elif len(anglesR) == 0:
            return []
        if len(anglesL) > 1:
            for i in range(len(anglesL)):
                if len(anglesL) == 1:
                    break
                if anglesL[0][2] < anglesL[1][2]:
                    anglesL.pop(1)
                else:
                    anglesL.pop(0)
        elif len(anglesL) == 0:
            return []
        if self.first_Leg_Is_Right_Leg == True:
            for j in range(6):
                angles.append(anglesR[0][j])
            if hands_on:
                angles.append(1.973)
            else:
                angles.append(0.0)
            angles.append(0.0)
            angles.append(0.0)
            if hands_on:
                angles.append(-0.147 - self.xtl / 114)
            else:
                angles.append(0.0)
            angles.append(0.0)
            for j in range(6):
                angles.append(-anglesL[0][j])
            if hands_on:
                angles.append(-1.973)
            else:
                angles.append(0.0)
            angles.append(0.0)
            angles.append(0.0)
            if hands_on:
                angles.append(0.147 + self.xtr / 114)
            else:
                angles.append(0.0)
        else:
            for j in range(6):
                angles.append(anglesL[0][j])
            if hands_on:
                angles.append(1.973)
            else:
                angles.append(0.0)
            angles.append(0.0)
            angles.append(0.0)
            if hands_on:
                angles.append(-0.147 - self.xtr / 114)
            else:
                angles.append(0.0)
            angles.append(0.0)
            for j in range(6):
                angles.append(-anglesR[0][j])
            if hands_on:
                angles.append(-1.973)
            else:
                angles.append(0.0)
            angles.append(0.0)
            angles.append(0.0)
            if hands_on:
                angles.append(0.147 + self.xtl / 114)
            else:
                angles.append(0.0)
        self.activePose = angles
        return angles

    def walk_Initial_Pose(self, amplitude=24, start_mixing=True):
        self.robot_In_0_Pose = False
        if not self.falling_Test() == 0:
            if self.falling_Flag == 3:
                uprint('STOP!')
            else:
                uprint('FALLING!!!', self.falling_Flag)
            return []
        self.xtr = self.xtl = 0
        framestep = self.simThreadCycleInMs // 10
        for j in range(self.initPoses):
            start1 = time.perf_counter()
            self.ztr = self.ztr0 - j * (self.ztr0 + self.gaitHeight) / self.initPoses
            self.ztl = self.ztl0 - j * (self.ztl0 + self.gaitHeight) / self.initPoses
            self.ytr = -self.d10 - j * amplitude / self.initPoses
            self.ytl = self.d10 - j * amplitude / self.initPoses
            angles = self.computeAlphaForWalk()
            if len(angles) == 0:
                self.exitFlag = self.exitFlag + 1
            else:
                joint_number = len(angles)
                if self.model == 'Roki_2':
                    servoDatas = []
                    for i in range(joint_number):
                        if self.keep_hands_up:
                            if i in self.hand_joints:
                                continue
                        if self.ACTIVESERVOS[i][0] == 8:
                            pos = int(angles[i] * 1698 * self.ACTIVESERVOS[i][2] / 2 + 7500)
                            servoData = Servo()
                            servoData.Id, servoData.Sio, servoData.Data = (13, self.ACTIVESERVOS[i][1], pos)
                            servoDatas.append(servoData)
                        else:
                            pos = int(angles[i] * 1698 * self.ACTIVESERVOS[i][2] + 7500)
                        servoData = Servo()
                        servoData.Id, servoData.Sio, servoData.Data = (self.ACTIVESERVOS[i][0], self.ACTIVESERVOS[i][1], pos)
                        servoDatas.append(servoData)
                else:
                    servoDatas = []
                    for i in range(joint_number):
                        if self.keep_hands_up:
                            if i in self.hand_joints:
                                continue
                        pos = int(angles[i] * 1698 * self.ACTIVESERVOS[i][2] + 7500)
                        servoData = Servo()
                        servoData.Id, servoData.Sio, servoData.Data = (self.ACTIVESERVOS[i][0], self.ACTIVESERVOS[i][1], pos)
                        servoDatas.append(servoData)
                if j == 0:
                    a = (yield ('servo', servoDatas, 10, 9))
                else:
                    a = (yield ('servo', servoDatas, self.frames_per_cycle, 0))

    def walk_Cycle(self, stepLength, sideLength, rotation, cycle, number_Of_Cycles, half=False):
        self.robot_In_0_Pose = False
        if not self.falling_Test() == 0:
            if self.falling_Flag == 3:
                uprint('STOP!')
            else:
                uprint('FALLING!!!', self.falling_Flag)
            return []
        self.stepLength = stepLength + self.motion_shift_correction_x
        self.sideLength = sideLength - self.motion_shift_correction_y
        self.rotation = math.degrees(rotation)
        if self.rotation <= 0:
            rotation = -self.rotation / 222 * 0.23 / self.params['ROTATION_YIELD_RIGHT']
        else:
            rotation = -self.rotation / 222 * 0.23 / self.params['ROTATION_YIELD_LEFT']
        if rotation > 0.125:
            rotation = 0.125
        if rotation < -0.125:
            rotation = -0.125
        alpha = 0
        if self.fr1 == 0:
            alpha01 = math.pi
        else:
            alpha01 = math.pi / self.fr1 * 2
        frameNumberPerCycle = 2 * self.fr1 + 2 * self.fr2
        framestep = self.simThreadCycleInMs // 10
        xtl0 = self.stepLength * (1 - (self.fr1 + self.fr2 + 2 * framestep) / (2 * self.fr1 + self.fr2 + 2 * framestep)) * 1.5
        xtr0 = self.stepLength * (1 / 2 - (self.fr1 + self.fr2 + 2 * framestep) / (2 * self.fr1 + self.fr2 + 2 * framestep))
        dx0_typical = self.stepLength / (2 * self.fr1 + self.fr2 + 2 * framestep) * framestep
        dy0_typical = self.sideLength / (2 * self.fr1 + self.fr2 + 2 * framestep) * framestep
        xr_old, xl_old, yr_old, yl_old = (self.xr, self.xl, self.yr, self.yl)
        if stepLength < 0:
            self.xr, self.xl = (self.params['BODY_TILT_AT_WALK_BACKWARDS'], self.params['BODY_TILT_AT_WALK_BACKWARDS'])
        else:
            self.xr, self.xl = (self.params['BODY_TILT_AT_WALK'], self.params['BODY_TILT_AT_WALK'])
        self.yr, self.yl = (-self.params['SOLE_LANDING_SKEW'], self.params['SOLE_LANDING_SKEW'])
        yield ('drain',)
        fase_offset = 0.7
        order = []
        pos = int(self.amplitude / 2)
        for _ in range(self.fr1):
            pos -= int(self.amplitude / self.fr1)
            order.append(pos)
        for iii in range(0, frameNumberPerCycle, framestep):
            if half and iii == frameNumberPerCycle / 2 - framestep:
                break
            start1 = time.perf_counter()
            if 0 <= iii < self.fr1:
                S = order[iii + framestep - 1] * (self.amplitude + self.sideLength) / self.amplitude
                self.ytr = S - self.d10 + self.sideLength / 2
                self.ytl = S + self.d10 + self.sideLength / 2
                self.ztl = -self.gaitHeight
                self.ztr = -self.gaitHeight
                if cycle == 0:
                    continue
                else:
                    dx0 = dx0_typical
                self.xtl = xtl0 - dx0 - dx0 * iii / framestep
                self.xtr = xtr0 - dx0 - dx0 * iii / framestep
            if self.fr1 + self.fr2 <= iii < 2 * self.fr1 + self.fr2:
                S = -order[iii - self.fr1 - self.fr2 + framestep - 1] * (self.amplitude + self.sideLength) / self.amplitude
                self.ytr = S - self.d10 - self.sideLength / 2
                self.ytl = S + self.d10 + self.sideLength / 2
                self.ztl = -self.gaitHeight
                self.ztr = -self.gaitHeight
                dx0 = dx0_typical
                self.xtl -= dx0
                self.xtr -= dx0
            if self.fr1 <= iii < self.fr1 + self.fr2:
                self.ztr = -self.gaitHeight + self.stepHeight
                if cycle == 0:
                    dx = self.stepLength / (self.fr2 - 2 * framestep) * framestep / 2
                    dx0 = dx0_typical
                    dy = self.sideLength / self.fr2 * framestep
                    dy0 = dy0_typical
                else:
                    dx = self.stepLength / (self.fr2 - 2 * framestep) * framestep
                    dx0 = dx0_typical
                    dy = self.sideLength / self.fr2 * framestep
                    dy0 = dy0_typical
                if iii == self.fr1:
                    self.xtr -= dx0
                    self.ytr = S - self.d10 + dy0
                    self.ztr = -self.gaitHeight + self.stepHeight / 2
                elif iii == self.fr1 + self.fr2 - framestep:
                    self.xtr -= dx0
                    self.ytr = S - self.d10 + 2 * dy0 - self.sideLength
                else:
                    self.xtr += dx
                    self.ytr = S - 64 + dy0 - dy * self.fr2 / (self.fr2 - 2 * framestep) * ((iii - self.fr1) / 2)
                    self.wr = self.wl = rotation - (iii - self.fr1) * rotation / (self.fr2 - 2 * framestep) * 2
                self.xtl -= dx0
                self.ytl += dy0
            if 2 * self.fr1 + self.fr2 <= iii:
                self.ztl = -self.gaitHeight + self.stepHeight
                if cycle == number_Of_Cycles - 1:
                    dx0 = dx0_typical * 4 / self.fr2
                    dx = (self.stepLength * (self.fr1 + self.fr2) / (4 * self.fr1) + 2 * dx0) / (self.fr2 - 2 * framestep) * framestep / 1.23076941
                    if iii == 2 * self.fr1 + 2 * self.fr2 - framestep:
                        self.ztl = -self.gaitHeight
                        self.ytl = S + self.d10
                else:
                    dx = self.stepLength / (self.fr2 - 2 * framestep) * framestep
                    dx0 = dx0_typical
                    dy = self.sideLength / (self.fr2 - 2 * framestep) * framestep
                    dy0 = dy0_typical
                if iii == 2 * self.fr1 + self.fr2:
                    self.xtl -= dx0
                    self.ytl = S + self.d10 + dy0
                    self.ztl = -self.gaitHeight + self.stepHeight / 2
                elif iii == 2 * self.fr1 + 2 * self.fr2 - framestep:
                    self.xtl -= dx0
                    self.ytl = S + self.d10 + 2 * dy0 - self.sideLength
                else:
                    self.xtl += dx
                    self.ytl = S + 64 + dy0 - dy * (iii - (2 * self.fr1 + self.fr2)) / 2
                    self.wr = self.wl = (iii - (2 * self.fr1 + self.fr2)) * rotation / (self.fr2 - 2 * framestep) * 2 - rotation
                self.xtr -= dx0
                self.ytr += dy0
            angles = self.computeAlphaForWalk()
            if not self.falling_Flag == 0:
                return
            if len(angles) == 0:
                self.exitFlag = self.exitFlag + 1
            else:
                joint_number = len(angles)
                servoDatas = []
                if self.model == 'Roki_2':
                    for i in range(joint_number):
                        if self.keep_hands_up:
                            if i in self.hand_joints:
                                continue
                        if self.ACTIVESERVOS[i][0] == 8:
                            pos = int(angles[i] * 1698 * self.ACTIVESERVOS[i][2] / 2 + 7500)
                            servoData = Servo()
                            servoData.Id, servoData.Sio, servoData.Data = (13, self.ACTIVESERVOS[i][1], pos)
                            servoDatas.append(servoData)
                        else:
                            pos = int(angles[i] * 1698 * self.ACTIVESERVOS[i][2] + 7500)
                        servoData = Servo()
                        servoData.Id, servoData.Sio, servoData.Data = (self.ACTIVESERVOS[i][0], self.ACTIVESERVOS[i][1], pos)
                        servoDatas.append(servoData)
                else:
                    servoDatas = [Servo() for _ in range(joint_number)]
                    for i in range(joint_number):
                        if self.keep_hands_up:
                            if i in self.hand_joints:
                                continue
                        pos = int(angles[i] * 1698 * self.ACTIVESERVOS[i][2] + 7500)
                        servoData = Servo()
                        servoData.Id, servoData.Sio, servoData.Data = (self.ACTIVESERVOS[i][0], self.ACTIVESERVOS[i][1], pos)
                        servoDatas.append(servoData)
                a = (yield ('servo', servoDatas, self.frames_per_cycle, 0))
                time1 = time.perf_counter() - start1
        self.xr, self.xl, self.yr, self.yl = (xr_old, xl_old, yr_old, yl_old)
        yield ('drain',)

    def walk_Final_Pose(self, respect_body_tilt=False):
        self.robot_In_0_Pose = False
        if not self.falling_Test() == 0:
            if self.falling_Flag == 3:
                uprint('STOP!')
            else:
                uprint('FALLING!!!', self.falling_Flag)
            return []
        framestep = self.simThreadCycleInMs // 10
        yield ('drain',)
        if respect_body_tilt:
            xr, xl = (self.xr, self.xl)
            self.xr, self.xl = (self.params['BODY_TILT_AT_WALK'], self.params['BODY_TILT_AT_WALK'])
        for j in range(self.initPoses):
            start1 = time.perf_counter()
            # Leave extension margin below the 221.8 mm model length.
            self.ztr = -self.gaitHeight - (j + 1) * (215.0 - self.gaitHeight) / self.initPoses
            self.ztl = -self.gaitHeight - (j + 1) * (215.0 - self.gaitHeight) / self.initPoses
            self.ytr = -self.d10 - (self.initPoses - (j + 1)) * self.amplitude / 2 / self.initPoses
            self.ytl = self.d10 - (self.initPoses - (j + 1)) * self.amplitude / 2 / self.initPoses
            if j == self.initPoses - 1:
                angles = self.computeAlphaForWalk(hands_on=False)
            else:
                angles = self.computeAlphaForWalk()
            if len(angles) == 0:
                self.exitFlag = self.exitFlag + 1
            else:
                joint_number = len(angles)
                servoDatas = []
                if self.model == 'Roki_2':
                    for i in range(joint_number):
                        if self.keep_hands_up:
                            if i in self.hand_joints:
                                continue
                        if self.ACTIVESERVOS[i][0] == 8:
                            pos = int(angles[i] * 1698 * self.ACTIVESERVOS[i][2] / 2 + 7500)
                            servoData = Servo()
                            servoData.Id, servoData.Sio, servoData.Data = (13, self.ACTIVESERVOS[i][1], pos)
                            servoDatas.append(servoData)
                        else:
                            pos = int(angles[i] * 1698 * self.ACTIVESERVOS[i][2] + 7500)
                        servoData = Servo()
                        servoData.Id, servoData.Sio, servoData.Data = (self.ACTIVESERVOS[i][0], self.ACTIVESERVOS[i][1], pos)
                        servoDatas.append(servoData)
                else:
                    for i in range(joint_number):
                        if self.keep_hands_up:
                            if i in self.hand_joints:
                                continue
                        pos = int(angles[i] * 1698 * self.ACTIVESERVOS[i][2] + 7500)
                        servoData = Servo()
                        servoData.Id, servoData.Sio, servoData.Data = (self.ACTIVESERVOS[i][0], self.ACTIVESERVOS[i][1], pos)
                        servoDatas.append(servoData)
                a = (yield ('servo', servoDatas, self.frames_per_cycle, 0))
                time1 = time.perf_counter() - start1
        if respect_body_tilt:
            self.xr, self.xl = (xr, xl)

    def walk_Final_Pose_After_Kick(self):
        self.robot_In_0_Pose = False
        if not self.falling_Test() == 0:
            if self.falling_Flag == 3:
                uprint('STOP!')
            else:
                uprint('FALLING!!!', self.falling_Flag)
            return []
        xr_old, xl_old, yr_old, yl_old = (self.xr, self.xl, self.yr, self.yl)
        self.xr, self.xl = (self.params['BODY_TILT_AT_KICK'], self.params['BODY_TILT_AT_KICK'])
        framestep = self.simThreadCycleInMs // 10
        pose_taking_cycles = 2
        yield ('drain',)
        for j in range(pose_taking_cycles):
            start1 = time.perf_counter()
            self.ztr = -self.gaitHeight - (j + 1) * (233.0 - self.gaitHeight) / pose_taking_cycles
            self.ztl = -self.gaitHeight - (j + 1) * (233.0 - self.gaitHeight) / pose_taking_cycles
            self.ytr = -self.d10 - (pose_taking_cycles - (j + 1)) * self.amplitude / 2 / pose_taking_cycles
            self.ytl = self.d10 - (pose_taking_cycles - (j + 1)) * self.amplitude / 2 / pose_taking_cycles
            if j == pose_taking_cycles - 1:
                angles = self.computeAlphaForWalk(hands_on=False)
            else:
                angles = self.computeAlphaForWalk()
            if len(angles) == 0:
                self.exitFlag = self.exitFlag + 1
            else:
                joint_number = len(angles)
                if self.model == 'Roki_2':
                    servoDatas = [Servo() for _ in range(joint_number + 2)]
                    for i in range(joint_number):
                        if self.ACTIVESERVOS[i][0] == 8:
                            n = joint_number - 1 + self.ACTIVESERVOS[i][1]
                            pos = int(angles[i] * 1698 * self.ACTIVESERVOS[i][2] / 2 + 7500)
                            servoDatas[n].Id, servoDatas[n].Sio, servoDatas[n].Data = (13, self.ACTIVESERVOS[i][1], pos)
                        else:
                            pos = int(angles[i] * 1698 * self.ACTIVESERVOS[i][2] + 7500)
                        servoDatas[i].Id, servoDatas[i].Sio, servoDatas[i].Data = (self.ACTIVESERVOS[i][0], self.ACTIVESERVOS[i][1], pos)
                else:
                    servoDatas = [Servo() for _ in range(joint_number)]
                    for i in range(joint_number):
                        pos = int(angles[i] * 1698 * self.ACTIVESERVOS[i][2] + 7500)
                        servoDatas[i].Id, servoDatas[i].Sio, servoDatas[i].Data = (self.ACTIVESERVOS[i][0], self.ACTIVESERVOS[i][1], pos)
                a = (yield ('servo', servoDatas, self.frames_per_cycle, 0))
                time1 = time.perf_counter() - start1
        self.xr, self.xl, self.yr, self.yl = (xr_old, xl_old, yr_old, yl_old)

    def kick(self, first_Leg_Is_Right_Leg, small=False, kick_offset=0):
        self.robot_In_0_Pose = False
        if not self.falling_Test() == 0:
            if self.falling_Flag == 3:
                uprint('STOP!')
            else:
                uprint('FALLING!!!', self.falling_Flag)
            return []
        gaitHeight = 210
        stepHeight = 55
        stepLength = 64
        kick_size = self.kick_power - 30
        tmp1 = self.first_Leg_Is_Right_Leg
        self.first_Leg_Is_Right_Leg = first_Leg_Is_Right_Leg
        tmp = self.gaitHeight
        self.gaitHeight = gaitHeight
        yield from self.walk_Initial_Pose(amplitude=46, start_mixing=False)
        alpha = 0
        alpha01 = math.pi / self.fr1 * 2
        frameNumberPerCycle = 2 * self.fr1 + 2 * self.fr2
        framestep = self.simThreadCycleInMs // 10
        dx0_typical = self.stepLength / (2 * self.fr1 + self.fr2 + 2 * framestep) * framestep
        xr_old, xl_old, yr_old, yl_old = (self.xr, self.xl, self.yr, self.yl)
        self.xr, self.xl = (self.params['BODY_TILT_AT_KICK'], self.params['BODY_TILT_AT_KICK'])
        self.yr, self.yl = (-self.params['SOLE_LANDING_SKEW'], self.params['SOLE_LANDING_SKEW'])
        fase_offset = 0.7
        yield ('drain',)
        for iii in range(0, frameNumberPerCycle, framestep):
            if 0 <= iii < self.fr1:
                alpha = alpha01 * (iii / 2 + fase_offset * framestep)
                S = self.amplitude / 2 * math.cos(alpha)
                self.ytr = S - self.d10
                self.ytl = S + self.d10
                self.ztl = -gaitHeight
                self.ztr = -gaitHeight
                continue
            if self.fr1 + self.fr2 <= iii < 2 * self.fr1 + self.fr2:
                alpha = alpha01 * ((iii - self.fr2) / 2 + fase_offset * framestep)
                S = self.amplitude / 2 * math.cos(alpha)
                self.ytr = S - self.d10
                self.ytl = S + self.d10
                self.ztl = -gaitHeight
                self.ztr = -gaitHeight
                dx0 = dx0_typical
                self.xtl -= dx0
                self.xtr -= dx0
            if self.fr1 <= iii < self.fr1 + self.fr2:
                self.ztr = -gaitHeight + stepHeight
                dx = stepLength / 2 / self.fr2 * 2
                dx0 = stepLength / (2 * self.fr1 + self.fr2 + 4) * framestep
                if iii == self.fr1:
                    self.xtr -= dx0
                    self.ytr = S - (64 + kick_offset)
                elif iii == self.fr1 + self.fr2 - 2:
                    self.xtr -= dx0
                    self.ytr = S - (64 + kick_offset)
                else:
                    self.xtr += dx * self.fr2 / (self.fr2 - 2 * framestep)
                    self.ytr = S - (64 + kick_offset)
                if iii == self.fr1 + self.fr2 - 10:
                    self.xtr += kick_size
                if iii == self.fr1 + self.fr2 - 4:
                    self.xtr -= kick_size
                self.xtl -= dx0
            if 2 * self.fr1 + self.fr2 <= iii:
                self.ztl = -gaitHeight + stepHeight
                dx0 = dx0_typical * 4 / self.fr2
                dx = (stepLength * (self.fr1 + self.fr2) / (4 * self.fr1) + 2 * dx0) / (self.fr2 - 2 * framestep) * framestep
                if iii == 2 * self.fr1 + 2 * self.fr2 - framestep:
                    self.ztl = -gaitHeight
                    self.ytl = S + self.d10
                if iii == 2 * self.fr1 + self.fr2:
                    self.xtl -= dx0
                    self.ytl = S + 64
                elif iii == 2 * self.fr1 + 2 * self.fr2 - framestep:
                    self.xtl -= dx0
                    self.ytl = S + 64
                else:
                    self.xtl += dx
                    self.ytl = S + 64
                self.xtr -= dx0
            angles = self.computeAlphaForWalk()
            if not self.falling_Flag == 0:
                return
            if len(angles) == 0:
                print('unresolved IK at kick')
                self.exitFlag = self.exitFlag + 1
            else:
                joint_number = len(angles)
                if self.model == 'Roki_2':
                    servoDatas = [Servo() for _ in range(joint_number + 2)]
                    for i in range(joint_number):
                        if self.ACTIVESERVOS[i][0] == 8:
                            n = joint_number - 1 + self.ACTIVESERVOS[i][1]
                            pos = int(angles[i] * 1698 * self.ACTIVESERVOS[i][2] / 2 + 7500)
                            servoDatas[n].Id, servoDatas[n].Sio, servoDatas[n].Data = (13, self.ACTIVESERVOS[i][1], pos)
                        else:
                            pos = int(angles[i] * 1698 * self.ACTIVESERVOS[i][2] + 7500)
                        servoDatas[i].Id, servoDatas[i].Sio, servoDatas[i].Data = (self.ACTIVESERVOS[i][0], self.ACTIVESERVOS[i][1], pos)
                else:
                    servoDatas = [Servo() for _ in range(joint_number)]
                    for i in range(joint_number):
                        pos = int(angles[i] * 1698 * self.ACTIVESERVOS[i][2] + 7500)
                        servoDatas[i].Id, servoDatas[i].Sio, servoDatas[i].Data = (self.ACTIVESERVOS[i][0], self.ACTIVESERVOS[i][1], pos)
                a = (yield ('servo', servoDatas, self.frames_per_cycle, 0))
        self.xr, self.xl, self.yr, self.yl = (xr_old, xl_old, yr_old, yl_old)
        yield from self.walk_Final_Pose_After_Kick()
        yield ('sleep', 100 / 1000)
        self.gaitHeight = tmp
        self.first_Leg_Is_Right_Leg = tmp1
